version: "3.8"

services:
  gateway:
    image: docker.pkg.github.com/splashdb/splashdb/node:0.0.2
    environment:
      - SPLASHDB_SECURE=true
    secrets:
      - splashdb-admin-password
      - splashdb-privkey.pem
      - splashdb-cert.pem
    volumes:
      - /data/db:/data/db
    ports:
      - "8443:8443"
    networks:
      - splashdb

networks:
  splashdb: