version: "3.8"

services:
  node:
    image: docker.pkg.github.com/splashdb/splashdb/node:0.0.2
    environment:
      - SPLASHDB_SECURE=true
    secrets:
      - splashdb-admin-password
      - splashdb-privkey.pem
      - splashdb-cert.pem
    volumes:
      - /data/db:/data/db
    ports:
      - "8443:8443"
    networks:
      - splashdb

secrets:
   splashdb-admin-password:
     file: ../fixtures/localhost-admin-password.txt
   splashdb-privkey.pem:
     file: ../fixtures/localhost-privkey.pem
   splashdb-cert.pem:
     file: ../fixtures/localhost-cert.pem

networks:
  splashdb: